name: Tourism Project Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  DATASET_REPO: gauravguha/visit-with-us-wellness-dataset
  MODEL_REPO: gauravguha/visit-with-us-wellness-model
  SPACE_REPO: gauravguha/visit-with-us-wellness-app

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO: ${{ env.DATASET_REPO }}
        run: python ci/register_dataset.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn==1.7.2 numpy huggingface_hub
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DATASET_REPO: ${{ env.DATASET_REPO }}
        run: python ci/data_prep_ci.py

  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn==1.7.2 numpy joblib huggingface_hub mlflow==2.14.1
      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MODEL_REPO: ${{ env.MODEL_REPO }}
          DATASET_REPO: ${{ env.DATASET_REPO }}
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
        run: python ci/train_and_register.py
      - name: Upload MLflow runs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/**

  deploy-hosting:
    needs: [model-traning, data-prep, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python deployment/push_to_space.py



